baseurl = "http://www.frxiaobei.com"
title = "å‡¡äººå°åŒ— Â· è½¬è§’å¤„"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"
defaultContentLanguageInSubdir = false


[pagination]
pagerSize = 20


[markup.highlight]
style = "github-dark"


[params]
  author = "å‡¡äººå°åŒ—"
  info = "æ¯ä¸€ä¸ªè½¬è§’ï¼Œéƒ½æ˜¯é‡è§ä¸‹ä¸€æ¡è·¯çš„å¼€å§‹ã€‚åœ¨è½¬è§’å¤„ï¼Œå†™ä¸‹å…³äºAIã€æ€è€ƒä¸æ‹ç‚¹çš„æ•…äº‹ã€‚"
  description = "frxiaobei's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "herove@gmail.com"

  # faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"



[params.giscus]
  repo = "frxiaobei/frxiaobei-comments"
  repoID = "R_kgDOQJ_6ng"
  category = "Announcements"
  categoryID = "DIC_kwDOQJ_6ns4CxH-e"
  mapping = "pathname"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"
  loading = "lazy"


[params.googleTagManager]
id = "GTM-P9LPHJSJ"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/frxiaobei/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/frxiaobei/"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 6
  url = "https://frxiaobei.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Languages
[languages.zh-cn]
  languageName = "ğŸ‡¨ğŸ‡³"
  title = "å‡¡äººå°åŒ— Â· è½¬è§’å¤„"
  [languages.zh-cn.params]
    author = "å‡¡äººå°åŒ—"
    info = "æ¯ä¸€ä¸ªè½¬è§’ï¼Œéƒ½æ˜¯é‡è§ä¸‹ä¸€æ¡è·¯çš„å¼€å§‹ã€‚åœ¨è½¬è§’å¤„ï¼Œå†™ä¸‹å…³äºAIã€æ€è€ƒä¸æ‹ç‚¹çš„æ•…äº‹ã€‚"
    description = "frxiaobei's personal website"
  [[languages.zh-cn.menu.main]]
    name = "åšå®¢"
    weight = 1
    url = "posts/"
  [[languages.zh-cn.menu.main]]
    name = "å…³äº"
    weight = 2
    url = "about/"

[languages.en]
  languageName = "ğŸ‡ºğŸ‡¸"
  title = "frxiaobei Â· Corner Flow"
  [languages.en.params]
    author = "frxiaobei"
    info = "Every corner is the beginning of meeting the next road. Writing stories about AI, thoughts and turning points at the corner."
    description = "frxiaobei's personal website"
  [[languages.en.menu.main]]
    name = "Blog"
    weight = 1
    url = "posts/"
  [[languages.en.menu.main]]
    name = "About"
    weight = 2
    url = "about/"